### ISSUE TITLE
build-an-atom should be using vegas.RewardNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#101]
vegas.RewardNode was ported from build-an-atom, see https://github.com/phetsims/vegas/issues/4.  But build-an-atom is not using it, and still has its own copy.

**Comment by jbphet** [comment]
As part of addressing this, a query parameter that causes the reward node to be shown regardless of score should be added so that this can be easily tested.  For an example of how this can be done, please see reactants-products-and-leftovers\js\game\view\ResultsNode.js, line 45 as of this writing.

**Comment by aadish** [comment]
this has been changed and would be tested in the next release

**Comment by jbphet** [comment]
Generally this looks good.  I did a little cleanup, and also logged an issue about the base type leaking memory.  No further work required for this issue - closing.
