### ISSUE TITLE
invalid aspect ratio for screen icons in navbar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#102]
Screen icons for the navbar must have the same aspect ratio as either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE. See phetsims/joist#263 (comment). This sim does not, and fails when assertions are enabled.

**Comment by jbphet** [comment]
This has been fixed, and now runs fine with assertions enabled.  Closing.
