### ISSUE TITLE
Errors in periodic table

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/build-an-atom#104]
@jbphet there appears to be a bug in Build an Atom.   Period 6 and 7 elements (rows 6 and 7) are incorrect after Ba.   Errors occur on Atom, Symbol, and some game screens.

**Comment by oliver-phet** [comment]
A user emailed PhET help about this issue. @jbphet And I discussed, and it may make sense to wrap this fix into the next maintenance release of BaA.

**Comment by aadish** [comment]
Build an atom is now using the periodic table in the shred. Which has this issue fixed.
@jbphet can you look at it

**Comment by jbphet** [comment]
For reference, here is a screenshot of the periodic table in the version of BAA that is currently published on the PhET website:
![baa-periodic-table-with-errors](https://cloud.githubusercontent.com/assets/3082831/12125734/42783d40-b3aa-11e5-8f7f-b7ea8be87085.png)

Here is the table from the current version on the master branch:
![baa-periodic-table-fixed](https://cloud.githubusercontent.com/assets/3082831/12125756/5e80add8-b3aa-11e5-90e0-529ff4f78456.png)

I compared the latter to several tables that I found on line, and it looks correct.  However, the background color is gray and used to be white.  Assigning back to @aadish to fix this.  This might involve adding an option for ```backgroundColor``` to the periodic table code.

**Comment by aadish** [comment]
Added options for enabled , disabled and selected cell color.

**Comment by jbphet** [comment]
Looks good.  Assigning to @amyh-phet to look at the table and verify.  It should probably be checked on all three screens.

**Comment by amyh-phet** [comment]
Checked all screens and verified that the periodic table is correct.  Assigning to @jbphet to deploy.

**Comment by jbphet** [comment]
Closing, since @amyh-phet says the table looks good.
