### ISSUE TITLE
use new scoreboard?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#110]
Consider switching from ScoreboardPanel to ScoreboardBar, for the following reasons:

(1) Having ScoreboardBar at the top of the screen is more tablet friendly.
(2) Because of (1), we've done this in other sims, and should probably do the same here.
(3) It would be nice to get rid of ScoreboardPanel, so we don't have to maintain it (it currently fails stringTest).  Currently it's used only by build-an-atom and balancing-act. 

How ScoreboardPanel currently looks in Build An Atom:

![screenshot_99](https://cloud.githubusercontent.com/assets/3046552/11405430/ecc1e1d6-9364-11e5-8684-2f2b01aa205c.png)

Example of ScoreboardBar in Graphing Lines:

![screenshot_101](https://cloud.githubusercontent.com/assets/3046552/11405542/a1885c4e-9365-11e5-86af-1696f5fdb92b.png)

**Comment by samreid** [comment]
As I'm starting to instrument this game, I'm also wishing this used the non-deprecated ScoreboardBar.  I'll continue with ScoreboardPanel for now, but a switch soon would be very nice.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to decide if someone (most likely me) should just do this or whether we need to do any design review and/or discussions.  I believe the API for the new scoreboard is very similar to that of the old one, so switching should take an hour or less.

**Comment by pixelzoom** [comment]
build-an-atom looks like a straightforward retrofit, with no design/layout changes required.  Plenty of room at the top for a scoreboard, and definitely in the spirit of why designed this new scoreboard.

balancing-act may be a little trickier.

**Comment by pixelzoom** [comment]
The highlight was toned down in https://github.com/phetsims/scenery-phet/commit/33f3162822238368ddac713bf7d4c6c7bcddee86:

```
-        .addColorStop( 0.05, new Color( 'white' ).withAlpha( 0.8 ) ) // light
+        .addColorStop( 0.05, new Color( 'white' ).withAlpha( 0.5 ) ) // light
```

Looks like this change may not have been picked up when the overall gradient approach was changed.

**Comment by samreid** [comment]
I moved the preceding @pixelzoom comment to https://github.com/phetsims/scenery-phet/issues/196#issuecomment-162590326 , it looks like it was in the wrong repo by mistake.

**Comment by pixelzoom** [comment]
Thanks. I'll delete the misplaced comments here.

**Comment by ariel-phet** [comment]
I am going to bounce this over to @amyh-phet to get her opinion.

@amyh-phet what say you? Perhaps do a quick mockup to see how you would feel about the change? Seems clean and nice to me.

**Comment by jbphet** [comment]
In my opinion, the new scoreboard would look good in the sim.

**Comment by amyh-phet** [comment]
@pixelzoom @samreid @jbphet @ariel-phet    I agree that the new scoreboard looks good.  Did a quick mockup with screenshots from Build an Atom and like the new look.  Sounds like it will solve some functionality issues as well.

**Comment by samreid** [comment]
> Sounds like it will solve some functionality issues as well.

Any time we have the opportunity to delete 134 lines of common code, we should pounce on it :smile:

**Comment by aadish** [comment]
new scoreboard has been added assigning to @jbphet to review

**Comment by jbphet** [comment]
The new scoreboard has been integrated and the layout of the challenges has been adjusted to look good.  Closing.
