### ISSUE TITLE
Migrate to use common code in the shred repo

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#111]
The original Java project for this simulation included another "flavor" (a.k.a. simulation) called "Isotopes and Atomic Mass".  That second simulation is now being ported to HTML5, and the common code shared between the two is being placed in a separate repository named "shred".  For the initial port of Isotopes and Atomic Mass, we are creating the shared code in shred but not propagating it back into Build an Atom right away.  There will need to be an effort at some point to replace several elements of code in the build-an-atom repo with the common code from shred when that common code is ready.

**Comment by samreid** [comment]
I am also instrumenting BAA components like the periodic table for phet-io. This effort will have to be duplicated in shred and re-tested when BAA uses shred.

**Comment by jbphet** [comment]
Hmmm, good point @samreid.  In your opinion, should this factoid tip the scales toward integrating the shred code now, as it is created, rather than later when it is essentially done?

**Comment by samreid** [comment]
It really depends whether (a) we are intending to fully instrument all screens of Build an Atom for phet-io or (b) we are just investigating the game screen for prototyping purposes.

This is a question for @kathy-phet.  If we are fully instrumenting all screens of Build an Atom for phet-io purposes now, then it should be refactored to use shred.

**Comment by samreid** [comment]
At yesterday's phet-io meting, @kathy-phet and @ariel-phet said:

> Getting BAA to use shred sooner rather than later would be good, even for S2015R

**Comment by jbphet** [comment]
I discussed this with @aadish today, and he will start efforts in this direction shortly.  He will start off by eliminating all files in build-an-atom that are unchanged versus their shred versions, and then will start working on those that have changed.  I've asked him to ping @samreid whenever he intends to spend time working on this so that the two of them can strive to avoid merge issues.  @aadish has also been given write permissions on the build-an-atom repo.  Assigning this issue to him for now.

**Comment by aadish** [comment]
the common code has been ported to shred and assigning @jbphet for review 
see commits 
8095f9dd3e51bdf35754f4c32cf4f0bef85f0514
14c6d0150f348886db657fa22adfce6daa23dd0d
bcb4aa52e1edee838d9a1c55e23d5cf816b73150
37023d46b1d315b64bbe56c52f5365b27aa704cc
50470ab9ce532da9e40b6a2ff305c764717ce825
940c2d767c955287dbc553e3c3437557d6a627c3
1f8a8afefd1817c25a7e423d5bd9e5e57cbd75f5

**Comment by jbphet** [comment]
Changes look good, and I checked to make sure that none of the files in shred are also in BAA and there is no overlap.  Closing.
