### ISSUE TITLE
poorly named Emitter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#112]
PeriodicTableCell line 33:

> var emitter = new Emitter();

This tells me nothing about what the emitter is being used for.  In a Skype discussion, we loosely agreed that Emitter names should be verbs that indicate what happened.  Eg, boundsChanged, visibilityChanged.  In this case, a better name is probably `cellPressed` (and I had to read the code to guess that.)

Assigning to @samreid since he created this Emitter.

**Comment by samreid** [comment]
Thanks for identifying this problem @pixelzoom, I fixed this above--I went with `cellPressedEmitter`.   I chose this because `cellPressed` sounds too much like a method name or boolean value.  @pixelzoom review if you wish.

**Comment by pixelzoom** [comment]
In the Skype discussion captured in https://github.com/phetsims/axon/issues/81, the majority opinion expressed was to leave off the "Emitter" suffix.  The change you've made is contrary to that, so I'm going to leave this open until we've discussed https://github.com/phetsims/axon/issues/81.

**Comment by pixelzoom** [comment]
In phetsims/axon#81, the consensus was changed to "use Emitter suffix".  Closing.
