### ISSUE TITLE
Check button overlaps the buckets

### ISSUE THREAD

**Issue by samreid** [phetsims/build-an-atom#117]
Discovered during #107 

![image](https://cloud.githubusercontent.com/assets/679486/12360932/21484c84-bb78-11e5-8fe1-358283d79543.png)

**Comment by samreid** [comment]
I'm demoting this priority until publication issues are sorted out.

**Comment by samreid** [comment]
Here's how it looks on the website:

![image](https://cloud.githubusercontent.com/assets/679486/12790517/d80a6c22-ca5f-11e5-9daa-6abf7c7e52c5.png)

@jbphet can you take a quick look and let me know what you think?

**Comment by aadish** [comment]
fixed closing
