### ISSUE TITLE
Double, Long String Tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/build-an-atom#118]
Related to https://github.com/phetsims/tasks/issues/479

Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Chrome 47.0.2526.106

Problem description: Some overlap with reset button in double test. Some buttons such as "Start Over" in Game are pushed out of screen in long test.

Steps to reproduce: Double and Long String tests

Severity:

Screenshots:
Double:
![screen shot 2016-01-15 at 1 43 56 pm](https://cloud.githubusercontent.com/assets/12610678/12365112/f6a7382e-bb8f-11e5-85b5-c672704ea9b7.jpg)

Long:
![screen shot 2016-01-15 at 1 51 39 pm](https://cloud.githubusercontent.com/assets/12610678/12365117/007606d2-bb90-11e5-98c5-bf5f8a933527.jpg)
![screen shot 2016-01-15 at 1 50 10 pm](https://cloud.githubusercontent.com/assets/12610678/12365118/0079ae5e-bb90-11e5-8a73-138aa00712ed.jpg)
![screen shot 2016-01-15 at 1 49 56 pm](https://cloud.githubusercontent.com/assets/12610678/12365119/00843e28-bb90-11e5-90ee-3a578122eb67.jpg)

Troubleshooting information (do not edit):
Name: ‪Build an Atom‬:‪Build an Atom‬
URL: http://phettest.colorado.edu/build-an-atom/build-an-atom_en.html?ea&brand=phet&stringTest=double
Version: 1.2.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1268x609
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by aadish** [comment]
@jbphet this has been done, assigning you to review it

**Comment by jbphet** [comment]
Changes look good, and I did some basic testing using ```stringTest=double```, ```stringTest=long```, and ```stringTest=rtl```, and all looked good.  Unassigning for now, and we will have QA test on the next release candidate.

**Comment by jbphet** [comment]
Verified during the testing of the 1.2 release, see https://github.com/phetsims/tasks/issues/577.  Closing.
