### ISSUE TITLE
Game should retain most recent score

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-an-atom#122]
The level selection screen needs to be changed to display stars for the most recent score achieved in a level. Currently the sim will always display the high score. Not a high priority issue, no need for a maintenance release. It's okay to wait until next re-deploy. See https://github.com/phetsims/balancing-act/issues/63 for the original issue.

**Comment by aadish** [comment]
changes have been made to retain the last score and also added the best time on game level selection   node

**Comment by jbphet** [comment]
This has been fixed and was tested as part of the 1.2 release process.  Closing.
