### ISSUE TITLE
Score does not refresh when page is refreshed

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/build-an-atom#126]
Related to https://github.com/phetsims/tasks/issues/577
Test device: Win 8 Laptop, Socrates

Operating System: Windows 8 64-bit

Browser: Edge 25.10586.0.0

Problem description: The star score will not go blank when 'refresh all' button is selected on the Game page. 

Steps to reproduce: Play a round to earn a score. Refresh Game page.

Severity:

Screenshots:

Troubleshooting information (do not edit):

Name: ‪Build an Atom‬

URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-rc.1/build-an-atom_en.html

Version: 1.2.0-rc.1 2016-04-13 19:28:57 UTC

Features missing: touch

Flags: pointerEnabled

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

Language: en-US

Window: 1920x934

Pixel Ratio: 1/1

WebGL: WebGL 0.96

GLSL: WebGL GLSL ES 0.96

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"4c84154a","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"build-an-atom":{"sha":"700ed9dd","branch":"HEAD"},"chipper":{"sha":"b2e0b31e","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"joist":{"sha":"ecd8d968","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"d7eed2d1","branch":"HEAD"},"scenery":{"sha":"7db0478c","branch":"HEAD"},"scenery-phet":{"sha":"71c5dea5","branch":"HEAD"},"sherpa":{"sha":"b74418c0","branch":"HEAD"},"shred":{"sha":"9e57833f","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"75fe60ed","branch":"HEAD"},"vibe":{"sha":"42f7af6b","branch":"HEAD"}}

**Comment by phet-steele** [comment]
Fixed.
