### ISSUE TITLE
Continue button doesn't appear after game is completed

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/build-an-atom#127]
Test device: Dirac

Operating System: OSX 10.9.5

Browser: Safari

Problem description: If you click the orange refresh button before playing any one of the games, after you complete the game, the window telling you your score with the continue button will not appear, and you will be stuck on the ending screen, with the confetti falling forever if you completed with a perfect score. The only way to get back to the games menu will be to refresh the webpage. 

Steps to reproduce: Click the orange refresh button before selecting a game, then play through the game.

Screenshots:
![screen shot 2016-04-15 at 3 39 51 pm](https://cloud.githubusercontent.com/assets/11947677/14576066/57a2e6ca-0323-11e6-8ad1-0dcc4b58bce9.png)

Troubleshooting information (do not edit):
Name: ‪Build an Atom‬
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-rc.1/build-an-atom_en.html
Version: 1.2.0-rc.1 2016-04-13 19:28:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/537.86.1
Language: en-us
Window: 1240x620
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.24.17)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"4c84154a","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"build-an-atom":{"sha":"700ed9dd","branch":"HEAD"},"chipper":{"sha":"b2e0b31e","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"joist":{"sha":"ecd8d968","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"d7eed2d1","branch":"HEAD"},"scenery":{"sha":"7db0478c","branch":"HEAD"},"scenery-phet":{"sha":"71c5dea5","branch":"HEAD"},"sherpa":{"sha":"b74418c0","branch":"HEAD"},"shred":{"sha":"9e57833f","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"75fe60ed","branch":"HEAD"},"vibe":{"sha":"42f7af6b","branch":"HEAD"}}

Related to phetsims/tasks#577

**Comment by brroberts1231** [comment]
Actually it seems to most commonly happen if you click the orange refresh all button between the two times you play the game.

**Comment by phet-steele** [comment]
Fixed.
