### ISSUE TITLE
Games don't end well after Refresh All button is clicked

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/build-an-atom#128]
Related to https://github.com/phetsims/tasks/issues/577

Test device: Chromebook, Vygtosky

Operating System: Chrome OS 64-bit

Browser: Chrome 49.0.2623.111

Problem description: In the last game, once the question is answered and the "correct" smiley face appears, clicking the Next button does nothing and the game will not exit. In the first game, https://github.com/phetsims/build-an-atom/issues/127 was seen when played. This occurred with all four games.

Steps to reproduce: Play any game. Click the Refresh all button and then attempt to play a round of a game. 

Severity:

Screenshots: 

Troubleshooting information (do not edit):
Name: ‪Build an Atom‬
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-rc.1/build-an-atom_en.html
Version: 1.2.0-rc.1 2016-04-13 19:28:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS armv7l 7834.66.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.111 Safari/537.36
Language: en-US
Window: 1366x657
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 48)
Max viewport: 8192x8192
OES_texture_float: false
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"4c84154a","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"build-an-atom":{"sha":"700ed9dd","branch":"HEAD"},"chipper":{"sha":"b2e0b31e","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"joist":{"sha":"ecd8d968","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"d7eed2d1","branch":"HEAD"},"scenery":{"sha":"7db0478c","branch":"HEAD"},"scenery-phet":{"sha":"71c5dea5","branch":"HEAD"},"sherpa":{"sha":"b74418c0","branch":"HEAD"},"shred":{"sha":"9e57833f","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"75fe60ed","branch":"HEAD"},"vibe":{"sha":"42f7af6b","branch":"HEAD"}}

**Comment by elisemorgan** [comment]
Will attempt to recreate on Mac for screen recording

**Comment by elisemorgan** [comment]
Recreated on Mac OS X 101.10.5 Chrome 49.0.2623.112
Three different results seen at end of games:
https://drive.google.com/file/d/0B_TAL-jnJOoKYVJjWi1MYnQ2SU0/view?usp=sharing
https://drive.google.com/file/d/0B_TAL-jnJOoKR2VIYV8zbVRRaXc/view?usp=sharing
![screen shot 2016-04-18 at 12 06 47 pm](https://cloud.githubusercontent.com/assets/12610678/14614538/df4d6e82-055e-11e6-9c1d-fa64e55af451.jpg)

**Comment by elisemorgan** [comment]
Note: not specific to chrome, recreated on Safari on OS X 10.10.5 and Safari 601.1 on iPad 3

**Comment by phet-steele** [comment]
Fixed.
