### ISSUE TITLE
1st level selection image needs to be updated

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-an-atom#129]
The image for the first level selection button is quite wrong. The periodic table here has a couple errors, notably two "Sc" panels that are causing "Y", "Zr", and "Nb" to be shifted over one group.

![wrongtable](https://cloud.githubusercontent.com/assets/5863899/14652774/1713f668-0633-11e6-8fdc-ce1640473f65.PNG)

Seen on Win 10 browsers. For phetsims/tasks/issues/577.

**Comment by jbphet** [comment]
I've fixed the layout and also improved the fading on the top and the lower right corner.  It now looks like this:
![baa-periodic-table](https://cloud.githubusercontent.com/assets/3082831/14683824/09666dd6-06ea-11e6-8b11-4c0870250fa8.PNG)

Unassigning for now, will re-test on next release candidate.

**Comment by jbphet** [comment]
Hang on - not quite right yet - should have Sr on bottom row, not Sc.

**Comment by jbphet** [comment]
Okay, this is the actual fixed version:

![baa-periodic-table](https://cloud.githubusercontent.com/assets/3082831/14688205/aba3585c-06fe-11e6-848f-01b090177412.PNG)

**Comment by phet-steele** [comment]
Thanks @jbphet for your Illustrator prowess. Fixed.
