### ISSUE TITLE
Neutrons don't say unstable

### ISSUE THREAD

**Issue by BryceAG** [phetsims/build-an-atom#130]
Test device:
Bates

Operating System:
Win 7

Browser:
Chrome, IE, Firefox

Problem description:
If you have the unstable option selected, and put just neutron(s) in the atom for the first two modes, the neutron(s) will shake, but won't say Unstable

Steps to reproduce:
select the stable/unstable button, and put any number of neutrons in the atom without protons.

Severity:
Low

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/14684929/6d97ff72-06ef-11e6-99be-87cb04bf579d.png)
might be hard to tell, but the neutron is off-center by shaking

Troubleshooting information (do not edit):
Name: ‪Build an Atom‬
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.2.0-rc.1/build-an-atom_en.html
Version: 1.2.0-rc.1 2016-04-13 19:28:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"4c84154a","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"build-an-atom":{"sha":"700ed9dd","branch":"HEAD"},"chipper":{"sha":"b2e0b31e","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"joist":{"sha":"ecd8d968","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"d7eed2d1","branch":"HEAD"},"scenery":{"sha":"7db0478c","branch":"HEAD"},"scenery-phet":{"sha":"71c5dea5","branch":"HEAD"},"sherpa":{"sha":"b74418c0","branch":"HEAD"},"shred":{"sha":"9e57833f","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"},"vegas":{"sha":"75fe60ed","branch":"HEAD"},"vibe":{"sha":"42f7af6b","branch":"HEAD"}}

related to phetsims/tasks#577

**Comment by jbphet** [comment]
I have a vague memory that this was done on purpose, but I'm not certain.  We don't call a bunch of electrons with no protons and ion either.  Maybe we didn't want to label it with anything because it's not really an atom.  Having said that, neutrons on their own *are* unstable, so maybe it would be better to label them as such.

At any rate, this behavior is the same as the currently live version of this sim.

Assigning to @ariel-phet to decide if neutrons on their own should be shown with the "Unstable" label.

**Comment by ariel-phet** [comment]
I would say leave as is, but assigning to @amyh-phet for her input

**Comment by amyh-phet** [comment]
@ariel-phet  and @BryceAG  and @jbphet   I'm comfortable with leaving as is.   It seems to me the stable/unstable label is only for an atom.  If you have only neutrons in the model, you haven't created an atom yet so no label would be appropriate.

**Comment by ariel-phet** [comment]
Sounds good, closing
