### ISSUE TITLE
screen icons fail validation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#134]
After adding icon validation to joist.Screen (see phetsims/joist#352), it was discovered that one or more home screen icons fail validation.  They appear to be smaller than the minimum size of Screen.HOME_SCREEN_ICON_SIZE.  Looks like the associated PNG files are too small. Run with assertions enabled (`?ea`) to reproduce the problem.

**Comment by jbphet** [comment]
Icons have been adjusted to be the required size.  I also changed the Adobe Illustrator files so that the artwork itself is the required 548x373, but ended up having to scale the exported PNG files a little bit (using MS Paint) to get the size to be exactly correct.  Closing.
