### ISSUE TITLE
User reported issue: elements go to Einsteinium, but untranslatable

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-an-atom#136]
Reported by Sandor Sep 24, 2016:
1.       Open Build an atom
2.       Start Game
3.       Select the third game
4.       Sooner or later you get a game similar to this

If you increase the atomic number you can go up to 99, Einsteinium:
![image](https://cloud.githubusercontent.com/assets/5090275/18842632/e0efced6-83d2-11e6-967c-9a5ad6835e5f.png)

Maybe you should limit it at 18, Argon.
![image](https://cloud.githubusercontent.com/assets/5090275/18842637/e71b5e24-83d2-11e6-8c0a-ad9fe9162d38.png)

 The common strings only list names of elements up to Z=18, but the games use apparently more.

**Comment by jbphet** [comment]
I just looked at the source code and, indeed, we only have translatable strings for elements through argon, which is atomic number 18.  It wouldn't be hard to make the rest of the strings translatable - maybe an hour of work.  This work would be done in the shred repo, and the translated strings may be useful for other simulations in the future.

Assigning to @ariel-phet to decide if we should limit the atomic number to 18 in build-an-atom, make all element names translatable (through Ununoctium), or leave it as is.

**Comment by ariel-phet** [comment]
@jbphet we should make them translatable, putting at medium priority, but feel free to have @aadish do this ASAP

**Comment by aadish** [comment]
on it @ariel-phet @jbphet

**Comment by aadish** [comment]
@ariel-phet @oliver-phet 

all the element strings are translatable and live on the website

@oliver-phet you can inform this to the translators and close this issue
