### ISSUE TITLE
Status of iO instrumentation?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-an-atom#137]
@jbphet and @samreid can you let me know the status of iO instrumentation for this sim?

This might get some priority because of our sonification collaboration, but likely it would be fine to have the sim (but not the game portion fully instrumented).

**Comment by jbphet** [comment]
A fair amount of work was done early on to instrument screens 1 and 2, but we left out screen 3 - the game screen - while some things were worked out with the need for repeatable pseudo-random behavior.  I just glanced at the code and see a lot of tandems and such, but I think @samreid will have to provide the details of the precise state of affairs.

**Comment by samreid** [comment]
The instrumentation from https://github.com/phetsims/build-an-atom/issues/107#issuecomment-253622172 is more extensive than I expected.  The instance proxies wrapper reveals the following components in screen 1 are already instrumented:

* the particle positions
* the particle input listeners
* Show Element Name Check Box
* Show Neutral Or Ion Check Box
* Show Stable Or Unstable Check Box
* Label Visualization Control Panel
* Orbits Radio Button
* Cloud Radio Button
* Reset All Button

So the 1st screen sim is about 20% instrumented already.

**Comment by ariel-phet** [comment]
@samreid thanks for the info, but clearly more to be done to get the sim instrumented. Closing.
