### ISSUE TITLE
rewrite to no longer use PropertySet

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#138]
See phetsims/axon#102 for background.

**Comment by aadish** [comment]
@samreid i was deprecating the property set in build-an-atom and just wanted to make sure that the way I am changing the tandem used in property set is correct 

could you review this commit to see that tandem is ported correctly
7a6da6aac8f8a2b4b4bdf19f6cd3c761ffb29cde

**Comment by samreid** [comment]
That change set looks correct.  A few additional things to note: the es5 get/set methods such as BAAGameModel.state will no longer exist, so the usage sites must be rewritten to use baaGameModel.stateProperty.get(), for instance.  Also, you will need to pass phetioValueType arguments to the Property options.

**Comment by aadish** [comment]
@samreid thanks for reviewing it and changes have been made accordingly

**Comment by jbphet** [comment]
I was looking at this to see if it could be closed, but I found a few usages of values that used to be properties, so I added some `preventGetSet` code and cleaned up what was hit.  We should leave this code in for a month or so and then remove, roughly in early March 2017.

**Comment by jbphet** [comment]
The code has survived a fair amount of testing since this migration, and I think it's now safe to remove the `preventGetSet` calls and close this issue.
