### ISSUE TITLE
Unused "Isotope Electron Cloud"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-an-atom#143]
@jbphet, why does this sim have an "Isotope Electron Cloud"? This:

<img width="565" alt="screen shot 2017-03-03 at 10 22 54 am" src="https://cloud.githubusercontent.com/assets/5863899/23561420/6a3bcf4c-fffb-11e6-9e8b-d94ad2be52aa.png">

When set to visible, and when you have some sort of element in the play area, you see the blue cloud from Isotopes and Atomic Mass (the sim):

<img width="778" alt="screen shot 2017-03-03 at 10 24 19 am" src="https://cloud.githubusercontent.com/assets/5863899/23561462/9841996c-fffb-11e6-9342-d24619bf97dc.png">

This cloud is never used in BAA, so why is it here? Is it from shred? It just stays in the top left of the sim and never moves, so it certainly isn't accomplishing anything. Note this is NOT the same thing as the electron cloud you can show with the radio buttons:

<img width="781" alt="screen shot 2017-03-03 at 10 27 13 am" src="https://cloud.githubusercontent.com/assets/5863899/23561571/0011c1ac-fffc-11e6-9720-da08f769fe7b.png">

For reference, this is the isotope electron cloud from IAAM:

<img width="1534" alt="screen shot 2017-03-03 at 10 29 26 am" src="https://cloud.githubusercontent.com/assets/5863899/23561637/500c2cf6-fffc-11e6-980b-7c185e136c40.png">

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/792.

**Comment by jbphet** [comment]
The node was unused - it must have been left over from a previous implementation attempt.  It has been removed.  I'll have this issue tested by QA when we roll the next RC.

**Comment by phet-steele** [comment]
Looks removed to me!
