### ISSUE TITLE
incorporate change for tracking brand into 1.4.0-phetio release

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#145]
There is currently an RC under test for the 1.4-phetio branch.  During the developer meeting this week we decided that a recent change to the usage statistics code (yotta) should be incorporated into this release.  The issue with more detail about this, including the SHA that should be cherry picked, can be found here: https://github.com/phetsims/phetcommon/issues/37.

**Comment by jbphet** [comment]
There was only one commit to phetcommon since the last RC build, so I just updated the dependencies file rather than branch phetcommon and cherry pick the commit.

**Comment by jbphet** [comment]
Assigning to @jonathanolson to verify since no one else seems to know how.  The RC can be found at http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.4.0-phetiorc.2/.

**Comment by jonathanolson** [comment]
The brand is included in the Yotta messages.
