### ISSUE TITLE
pick up change to fix simulation link in wrappers

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#147]
The simulation link is broken from the index.html file in v1.4.0-phetiorc.1.  The fix was done in the phet-io repo, details are available here: https://github.com/phetsims/phet-io/issues/1060.  This will need to be rolled into the next RC for the 1.4-phetio branch.

**Comment by jbphet** [comment]
I got lucky on this - the commit in the phet-io repo that fixed this problem was the one immediately after the SHA that was used in the previous RC, so no branch was required.  Should now be fixed.

**Comment by phet-steele** [comment]
The simulation link now works!
