### ISSUE TITLE
Developer's Guide documentation is out of date for v1.4.0-phetiorc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#148]
The developer's guide documentation is missing several types that have been added while instrumenting this simulation, for example `TAccordionBox` and `TSphereBucket`, among several others.  I talked with @zepumph about this, and he informed me that regenerating the document is a semi-manual process at this point.  He and I are going to take the steps necessary to do this for the next RC on the 1.4-phetio branch.

**Comment by jbphet** [comment]
Just to be clear, I'm referring to the documentation that is shown when the user clicks on the link shown in the screenshot below:

![phetio-dev-guide](https://cloud.githubusercontent.com/assets/3082831/23812793/42a1e4e6-0599-11e7-95b3-3f7db5775852.PNG)

**Comment by jbphet** [comment]
Assigning to @zepumph and @phet-steele to verify that documentation looks correct in the RC version, which can be found here: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.4.0-phetiorc.2/.

**Comment by zepumph** [comment]
It looks like AccordionBox didn't make it into the version you just sent. Looking deeper I see that https://github.com/phetsims/phet-io-website/commit/c5aa6f0925c4f08f46330077ced328c2e0185c27 is the phet-io-website SHA. This is from Feb 23. Perhaps the new cherrypick didn't make it into this rc?

**Comment by jbphet** [comment]
I must've missed a step in the build process, because I can see that the commit that updated to the needed SHA for phet-io-website (f0e04a497b8b5eabf9b64e12e8617a0764581319) got essentially reverted by the automatic commit for the build (3c431dd88a64e9ea6c5b74ec5fe35d85309afea3).  Dang.  I'll work with @phet-steele to decide whether this warrants a new RC or whether we would feel confident fixing this when and if we go from RC2 to a production release.

**Comment by jbphet** [comment]
Copy of Skype dialog between me and @phet-steele:

[1:54:16 PM] John Blanco: Can I call to discuss BAA phetio RC?
[1:54:40 PM] Steele Dalton: is it about [this GitHub issue]?
[1:55:34 PM] John Blanco: Yes, and I want to make a case for just fixing it when and if we go from RC2 to production, since the dependencies on phet-io-website are quite minor.
[1:56:17 PM] Steele Dalton: I'm in agreement

**Comment by zepumph** [comment]
Unassigning myself. Let me know if there is more I can do.

**Comment by jbphet** [comment]
Fixed and verified during production release of v1.4.0-phetio, closing.
