### ISSUE TITLE
atom position off in game

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#149]
I'm regression testing master after pulling in some things from the 1.4-phetio branch, and saw a problem in the game where the position of an atom was off, see screenshot below.  This should be fixed before next release off of master that includes the game.

![baa-atom-position-off](https://cloud.githubusercontent.com/assets/3082831/23817621/c23c4f12-05b1-11e7-89a7-af59619f795a.PNG)

**Comment by jbphet** [comment]
Here's another similar case that I ran into:

![baa-atom-position-off-2](https://cloud.githubusercontent.com/assets/3082831/23817652/1509c81e-05b2-11e7-87f6-99eb14fb299f.PNG)

**Comment by phet-steele** [comment]
@jessegreenberg @jbphet this did not get fixed before the release of 1.6.0-rc.1. JB decided Jesse should fix it.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, shutting down the RC until this is added.

**Comment by jessegreenberg** [comment]
Layout fixed in the above commit, layout was changed so that it looks like the published version.

**Comment by phet-steele** [comment]
@jessegreenberg, the atoms in every game look to be correctly vertically aligned on the screen, but not horizontally. Between different challenges, you can see an atom jump left and right with respect to each other. Below, the atom for Helium is much more to the left:

<img width="1918" alt="screen shot 2017-07-19 at 11 31 04 am" src="https://user-images.githubusercontent.com/5863899/28380792-db4bcdb8-6c75-11e7-96b9-ed8582f147ca.png">
<img width="1920" alt="screen shot 2017-07-19 at 11 31 29 am" src="https://user-images.githubusercontent.com/5863899/28380799-dfc68e46-6c75-11e7-9476-bd97d9b02e89.png">

**Comment by jessegreenberg** [comment]
@phet-steele do you know if the deployed version exhibits any of this atom jumping?

**Comment by phet-steele** [comment]
> @phet-steele do you know if the deployed version exhibits any of this atom jumping?

It does.

**Comment by jbphet** [comment]
IMO, this is still worth fixing even if it appears in the published version unless it is unexpectedly difficult to do so.

**Comment by jessegreenberg** [comment]
@jbphet sounds good.

The atom is placed relative to its center, and the stability indicator for a particular AtomNode will change its bounds:
![screen shot 2017-07-20 at 5 36 34 pm](https://user-images.githubusercontent.com/6396244/28443376-dad8afe2-6d72-11e7-8414-559fb4d80e87.png)

If we place the atom according to its left bound, things should align.

**Comment by jessegreenberg** [comment]
Handled in the above commit.  Seemed to fix it, and I verified that the other AtomNodes in the other game views don't have this problem.

**Comment by phet-steele** [comment]
I LIKE it!
