### ISSUE TITLE
Scenery Performance

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-an-atom#15]
I've created this issue to track Scenery's performance in this particular simulation.

I've made a number of performance enhancements to the 'performance' branch, experimental for now, but may be merge-able for our deadlines. The most significant performance change is making the draggable particles use CSS transforms (approximately doubles FPS on iPad3/Nexus7 with 28->54 and 12->30 FPS respectively).

The current downside of this is that it slows down reordering of particles (it has to create an entire SVG layer), and thus whenever a nucleon is dropped in or removed from the nucleus. For that operation (dropping a nucleon in the middle), I'm showing approximately 41% time in AtomTabView.relayerNucleus' addChild/removeChild.

If there's any way to avoid having to reorder things (slow for Scenery right now, since it maintains a consistent layer state in-between each add/remove operation), that would give the best sim-wide performance.

It appears that chipper is not stripping Scenery's assertions, so we may see a stitching speedup in general if that is done.

Additionally, I've noticed in general some "jerkiness" of animation. This is almost certainly due to garbage collection, and I'll be looking at how to minimize the number of objects that Scenery creates.

**Comment by ariel-phet** [comment]
@aadish please evaluate this issue as you prepare Build an Atom for redepoly

**Comment by aadish** [comment]
Tested the current deployed simulation and master version of the simulation on iPad2 and iPad3 and performance wise master version is better than the deployed version.
assigning @jbphet to have a look at it and close the issue if performance is acceptable

**Comment by jbphet** [comment]
Performance is great on Chrome, Firefox, and Edge on my Win 10 machine.  There are some concerns about iPad performance, but those are being tracked under #38.  Also, we are about to do a round of RC testing for release 1.2, so any performance issues will be noted then.  I think it's safe to close this one.
