### ISSUE TITLE
branch: legends-of-learning

### ISSUE THREAD

**Issue by samreid** [phetsims/build-an-atom#154]
to support https://github.com/phetsims/special-ops/issues/70

**Comment by jbphet** [comment]
@samreid - Is this branch still needed?  The issue that it references is closed.  If this can go, please delete the branch, update this issue, and assign it back to me so that I can update https://github.com/phetsims/special-ops/issues/198.

**Comment by samreid** [comment]
This branch is no longer needed, I'll delete the branch and reassign the issue to @jbphet.

**Comment by jbphet** [comment]
Thanks @samreid.  I've updated https://github.com/phetsims/special-ops/issues/198.  Closing.
