### ISSUE TITLE
Should electrons have a "-" in them?

### ISSUE THREAD

**Issue by samreid** [phetsims/build-an-atom#155]
I noticed a discrepancy between how we render electrons and thought I would bring it up for discussion.  Build an Atom looks great in my opinion and might not be improved by adding "-" to the electrons (especially since there is a prominent label) but I thought I'd bring it up to make sure it was a conscious decision.

John Travoltage:
![image](https://cloud.githubusercontent.com/assets/679486/25347409/18b9e806-28d8-11e7-871d-6e99ddb99c96.png)

CCK Prototype:
![image](https://cloud.githubusercontent.com/assets/679486/25347432/289d95e2-28d8-11e7-90a6-ddb11831be75.png)

Build an Atom:
![image](https://cloud.githubusercontent.com/assets/679486/25347445/3334a144-28d8-11e7-842b-48f7f01d2ddc.png)

**Comment by ariel-phet** [comment]
@samreid yes, definitely a conscious decision. In this particular sim, learning that the different particles have a particular charge is an explicit learning goal, so it would be "revealing" a bit too much to label them. Also I believe that would fall outside the bounds of normal chem representations.
