### ISSUE TITLE
Discuss and determine initial PDOM structure

### ISSUE THREAD

**Issue by terracoda** [phetsims/build-an-atom#158]
Initial wireframe structure for the Build an Atom Parallel DOM has been laid out in a google design document, [BAA: PDOM](https://docs.google.com/document/d/1QzdjwByRXAXKAOLpv-3VPUihu_IuTSZ4pmvHFt6mn98/edit).

We can discuss structure questions in this issue.

My first question for @zepumph and @jessegreenberg is this document making any sense to you both?

**Comment by jessegreenberg** [comment]
This is looking great to me @terracoda, nice work!

**Comment by terracoda** [comment]
@jessegreenberg thanks! It combines some description with the structure. I'm not 100% sure about the structure for the atom (nest list), but the rest I think is in good shape.

**Comment by terracoda** [comment]
@jessegreenberg, @zepumph, @emily-phet  I am closing this issue, as I have mocked up the HTML and committed the code to the a11y-research repo for discussion.

I created a new issue (https://github.com/phetsims/a11y-research/issues/43) in that repo to discuss the structure. The design document will be updated to reflect changes to the PDOM.
