### ISSUE TITLE
buildAnAtom.homeScreen.activeProperty: TProperty not toggling

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/build-an-atom#160]
Judging by the other active properties (such as **buildAnAtom.symbolScreen.activeProperty: TProperty**) which toggle to true when the appropriate screen is active, **buildAnAtom.homeScreen.activeProperty: TProperty** doesn't toggle true OR false when the home screen is entered or left. I imagine it should be toggling based on whether the home screen is on. 

Related to https://github.com/phetsims/tasks/issues/847

**Comment by phet-steele** [comment]
@EthanWJohnson is this in Instance Proxies? I see it toggle correctly in the Events: colorized wrapper.

**Comment by phet-steele** [comment]
> @EthanWJohnson is this in Instance Proxies? I see it toggle correctly in the Events: colorized wrapper.

Nevermind, confusing it with `buildAnAtom.sim.showHomeScreenProperty`.

**Comment by EthanWJohnson** [comment]
Yeah, its not toggling in either.

**Comment by EthanWJohnson** [comment]
Noting that homeScreen.active still doesn't toggle in 1.4.0-phetiorc.2, for https://github.com/phetsims/tasks/issues/850

**Comment by zepumph** [comment]
This is fixed in master now. I will pull it into the branch later.

**Comment by phet-steele** [comment]
Looks fixed, thanks.
