### ISSUE TITLE
Bucket label instances are named oddly

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-an-atom#164]
Here is an example for the Protons bucket on the first screen. Note that no useful information is presented in the instance name, like screen or bucket the label belongs to:
<img width="367" alt="screen shot 2017-06-02 at 12 14 47 pm" src="https://cloud.githubusercontent.com/assets/5863899/26740406/a9c9621c-4792-11e7-9ac9-d312c7e4d472.png">

The same instance from a previous version https://phet-io.colorado.edu/sims/build-an-atom/1.4.0-phetio/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom shows that the instance name was fine at one point (see #163 if the version number is confusing).
<img width="494" alt="screen shot 2017-06-02 at 12 22 38 pm" src="https://cloud.githubusercontent.com/assets/5863899/26740423/bbc7fb04-4792-11e7-8cb6-dc498b1b5332.png">

Seen on Win 10 Chrome and FF. For phetsims/tasks/issues/850.

**Comment by zepumph** [comment]
I found the cause I think:

```js
options = _.extend( {
      labelNode: new Text( bucket.captionText, {
        font: new PhetFont( 20 ),
        fill: bucket.captionColor,
        tandem: Tandem.tandemRequired().createTandem( 'label' )
      } )
    }, options );
```

This tandemRequired() call is never being overridden for default label nodes, I need to pull this labelNode out of the options.

**Comment by zepumph** [comment]
Alright I updated these lines and there are no more cases of 'required' in instance proxies. I will cherry pick into branches later.

**Comment by phet-steele** [comment]
Looks good to me, thanks.
