### ISSUE TITLE
Picking up particles while they animate back to buckets is broken

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/build-an-atom#169]
For https://github.com/phetsims/QA/issues/23

**Comment by jessegreenberg** [comment]
Could be caused by recent scenery changes, but a recent commit also changed the drag handler https://github.com/phetsims/shred/commit/1cb8069c15b3575479ce493ff303c06d4a328b6a

**Comment by jessegreenberg** [comment]
Prior to that commit, the translate listener looked like

```js
      translate: function( translationParams ) {
        particle.setPositionAndDestination(
          particle.positionProperty.get().plus( modelViewTransform.viewToModelDelta( translationParams.delta ) )
        );
        return translationParams.position;
      },
```

The new onDrag looks like
```js
     onDrag: function( event, trail ) {
        // update the position immediately to match the destination (i.e. don't animate)
        self.particle.moveImmediatelyToDestination();
      },
```

**Comment by jessegreenberg** [comment]
And if I revert shred to https://github.com/phetsims/shred/commit/55239bb58bd58330f6dedefa662fd8c630b8ed98 the problem goes away.

**Comment by jessegreenberg** [comment]
@jbphet volunteered to investigate this, thanks!

**Comment by jbphet** [comment]
Should be fixed by this commit to shred: https://github.com/phetsims/shred/commit/820bea9729ef5f5e8bd90e0de790ca3d1abf0645

Assigning to @jessegreenberg to pull into the RC that is in progress for this sim.

**Comment by jessegreenberg** [comment]
I updated the shred SHA for the 1.6 release, thanks @jbphet.

**Comment by jessegreenberg** [comment]
1.6 was deployed and this issue can be closed.
