### ISSUE TITLE
instrument AtomValuePool?

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-an-atom#174]
Since NumberAtom is `Tandem.tandemRequired()`, `AtomValuePool.js` needs some work. 

Another option is to make NumberAtom `tandemOptional()`, I don't know the full scope of the trade offs, so I pass this off to @jbphet to recommend. 

Note, build-an-atom is currently broken until this is figured out because of https://github.com/phetsims/tandem/commit/3b161ec8fa2f0d48868958bed3e6839f84163818 from https://github.com/phetsims/forces-and-motion-basics/issues/239

Marking as high priority even though I think we are the only people working on PhET-iO BAA right now.

**Comment by jbphet** [comment]
There is some time scheduled to work on BAA+PhET-iO today - let's discuss and resolve this then.

**Comment by zepumph** [comment]
In a phet-io meeting today with @jbphet and @samreid, we decided to make `NumberAtom` `tandemOptional`. I'll take care of it.

**Comment by zepumph** [comment]
Done and BAA is running now. Closing
