### ISSUE TITLE
Convert usages of `get Node.disposed` to use `Node.isDisposed`

### ISSUE THREAD

**Issue by samreid** [phetsims/build-an-atom#199]
From https://github.com/phetsims/scenery/issues/899, we would like to be consistent about using `isDisposed` instead of `disposed`.  Some cases in Build an Atom declare their own subtype attribute for disposed, even though they extend a type that already tracks `isDisposed` such as `Node` or `PhetioObject`.   See also comment in https://github.com/phetsims/scenery/issues/899#issuecomment-462371251

Assigning to responsible dev for investigation.

**Comment by jbphet** [comment]
Investigated, changed usages of `dispose` to `isDisposed`.  I don't think this requires a review, but @samreid is welcome to take a look if he'd like.  Closing.
