### ISSUE TITLE
Corner radius of mass number accordion box too large

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/build-an-atom#200]
Just noticed while working on an unrelated issue, most likely related to https://github.com/phetsims/sun/issues/480

![image](https://user-images.githubusercontent.com/6396244/53824330-b4305000-3f41-11e9-9bce-b3642edbf3f4.png)

**Comment by jbphet** [comment]
Fixed, thanks for noticing this @jessegreenberg.  Closing.
