### ISSUE TITLE
API mismatches present

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-an-atom#204]
Looks like some tandems changed and crashed the phet-io version of the sim.

**Comment by zepumph** [comment]
Fixed by running `grunt update` which regenerated the PhET-iO baseline api. Tagging @SaurabhTotey because he committed the change. A great way to catch this is the launch the sim in phet-io standalone mode, in phetmarks or with query parameters `?brand-phet-io&phetioStandalone`. Over to @SaurabhTotey to review.

**Comment by zepumph** [comment]
Please see https://github.com/phetsims/phet-io/issues/1443#issuecomment-484306552 for a verbose explanation of supporting the phet-io api for simulations.

**Comment by SaurabhTotey** [comment]
Oh yeah, this is my bad. I believe I caused the issue while I was working on https://github.com/phetsims/shred/issues/22. I'll be sure to be more careful with changes that regard. Thanks for the heads up!

**Comment by zepumph** [comment]
Not a worry, and thank you!
