### ISSUE TITLE
String missing colon and space in ES6 version of BAM

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/build-an-atom#211]
For https://github.com/phetsims/QA/issues/482. Katie and I weren't sure if this had anything to do with ES6, so this issue might need to be moved to a different repo.

Platform: iOS 12

ES6 - "Puntuación0":

![new](https://user-images.githubusercontent.com/31285590/75078726-a7df3300-54c3-11ea-9109-5d672d58211c.jpeg)

Published - "Puntuación: 0":

![published](https://user-images.githubusercontent.com/31285590/75078751-c2191100-54c3-11ea-9015-6359c0cb130b.jpeg)

**Comment by jbphet** [comment]
I went through the translation files, and it appears to me that `es` was the only locale with this problem.  Looks like it was just a bad translation, and some refactoring of the scoreboard that occurred a while back made it appear.  I went ahead and directly fixed the translation file by making the string match the one for the other string with essentially the same pattern.  It looks good on master now (screenshot below), so should be fine in the next deploy.  Closing.

![image](https://user-images.githubusercontent.com/3082831/75399459-84e4c280-58b9-11ea-89ac-17974244e34d.png)
