### ISSUE TITLE
When sim is finished starting up, all non-dynamic shema entries must be registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-an-atom#213]
For ES6 Testing
This error appears when trying to start studio and other wrappers.
![studiowontstart](https://user-images.githubusercontent.com/41024075/76127666-771cf480-5fbf-11ea-9807-8f2b373298e5.png)

**Comment by chrisklus** [comment]
@KatieWoe this appears to be working on my end, is it fixed for you too?

**Comment by KatieWoe** [comment]
Looks like. Closing
