### ISSUE TITLE
User suggestion: noble gas rule

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-an-atom#216]
> I´m a german chemistry teacher and I used the App “Build an atom” as german version. I found that it provides misinformation for chemistry classes, because the students can form ions that are proven to be stable even though the rare gas rule is violated and then these ions are still called stable. 
> A first improvement would be, if the query "stable / unstable"specifically referred to the core. In the second step, it would be helpful for the chemistry class, to store the noble gas rule as a functionality so that also can be decided, whether the ion, that had been built, is stable or not. This should be easy to solve from the programming point, but would open up the possibility for the chemistry teachers that the rare gas rule could be rediscovered.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to decide whether this should be considered and, if so, who to bring in for further discussion.

**Comment by ariel-phet** [comment]
@oliver-phet we are not going to consider this change as it is beyond the scope of the learning goals for the simulations. Three points:

1. The stability is labeled near the nucleus to suggest that we are discussing stability only from the point of stable or unstable isotopes

2. The teacher tips are clear about what we mean by "stable" -- please point this educator to the teacher tips and let them know the tips are a good resource for these types of questions

3. Given the popularity of BAA and this request being the first of its kind I think the sim is fulfilling the learning goals of most users well.

**Comment by oliver-phet** [comment]
User emailed. Closing.
