### ISSUE TITLE
dead code in BuildAnAtomModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#219]
Noted while working on https://github.com/phetsims/tasks/issues/1052.

There is a chunk of dead (commented out) code in BuildAnAtomModel.  Delete it or document why it shouldn't be deleted.

**Comment by jbphet** [comment]
Thanks for pointing this out.  The code in question was commented out when fixing an issue with repositioning the nucleus when the "show stability" setting changed (see #146), and I must've missed permanently deleting it.  It's gone now.  Closing.
