### ISSUE TITLE
Check our representation of the symbol card in BAA. Is it the "standard" representation? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/build-an-atom#229]
Received feedback from a teacher today who mentioned that the locations we use for mass and number of protons on our chemical symbol card are reverse from what is in the period table, and its confusing for the middle school students. 

We should check this against standards for the atomic symbol of an atom, and see which is more popularly used in period tables (if it isn't a strict standard). 

I'm surprised this is the first feedback we have on this, if its indeed reversed, but making an issue to check it.

**Comment by kathy-phet** [comment]
This is what we have right now in BAA, and it is the standard isotope symbol: 
![image](https://user-images.githubusercontent.com/5096804/153114990-2f526afe-87c2-4d11-89f3-aed1daddad2e.png)

Mass upper left
Proton number lower left
Ion charge upper right

So far this is consistent with everything that I have seen for nuclear notation:
http://hyperphysics.phy-astr.gsu.edu/hbase/Nuclear/nucnot.html
https://opentextbc.ca/chemistry/chapter/2-3-atomic-structure-and-symbolism/
![image](https://user-images.githubusercontent.com/5096804/153115544-aa25f013-86b3-47f3-aedf-b6b5524478cf.png)

BUT, what is in the periodic table ... which is what she said confused students? 
https://www.google.com/search?q=periodic+table&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiCnJPn1vH1AhVBCjQIHZ11Bh4Q_AUoAXoECAIQAw&cshid=1644377330231299&biw=1396&bih=685&dpr=1.38 
The Periodic Tables **DO** almost always show the proton number in the upper right (and there is no mass number). She said this confused the 6th graders ... having that upper symbol be mass and inconsistent with what they see in the periodic table. 

While I can see how this is a problem for 6th graders, who are not learning isotope symbols, it doesn't look like we can/should make a change here. The symbol is consistent with the standard isotope symbol and to move thing around would be confusing! 

The only possible option would be a simplified 6th grade version that did not introduce the isotope symbol, but I don't really see this as a viable solution.

**Comment by kathy-phet** [comment]
@arouinfar - Can you take a quick look, and see if you agree? The only thing I could recommend is adding a note to teacher tips to look out for this confusion if using with younger students, and make sure to scaffold through the differences between where the proton number is found?

**Comment by arouinfar** [comment]
@kathy-phet I agree with your assessment. The isotope symbol and the period table entry are two different things. The notation we are using is the correct isotope notation -- the atomic number goes on the bottom and the mass number goes on the top. Periodic tables generally display two numbers -- the atomic number and the average molar mass. Often, the atomic number is near the top of the square (sometimes left-aligned, sometimes centered) and the molar mass is near the bottom. 

Here are a few more sources:

The RSC has an[ interactive periodic table](https://www.rsc.org/periodic-table) that displays key isotopes when you hover over an element. The mass number is displayed on top.
![image](https://user-images.githubusercontent.com/8419308/153247193-52715b71-f78b-4aa3-997e-7b5f5c2a0480.png)

The [OpenStax chem textbook](https://openstax.org/books/chemistry-2e/pages/2-3-atomic-structure-and-symbolism) has the same graphic as the screenshot from BCcampus.

The Wikipedia [article on isotopes](https://en.wikipedia.org/wiki/Isotope) also uses the same isotope notation throughout the article.
![image](https://user-images.githubusercontent.com/8419308/153248538-7e5cc21f-27e4-466e-b6fc-6977605e35cf.png)

I can understand why this could cause confusion for some students. However, I think the solution here is in the scaffolding, which I can note in the Teacher Tips. Additionally, we should add support for `?gameLevels` next time we republish this simulation. Then, we could tell the teacher that `?screens=1,3&gameLevels=1,2` would completely eliminate the symbol representation.

**Comment by kathy-phet** [comment]
I like the gameLevels idea! To eliminate the symbol for younger students. In fact, a client asked for this gameLevels selection for this sim specifically a while back (but I mentioned we didn't support it at the time).

**Comment by oliver-phet** [comment]
Just documenting that we've received a couple emails into phethelp about this (I reply pointing to the tips), latest today:

> Problem Description: The layout presented is inconsistent with the universally accepted format of the Periodic Table. Specifically, the atomic number should always appear at the top of each element box, while the atomic mass should be displayed at the bottom. Unfortunately, the current materials have these values reversed, which is contrary to standard scientific conventions.
> This discrepancy is present across all related activities, including those involving atoms, symbols, and games. It has caused considerable confusion among students and is impacting their understanding of fundamental concepts in chemistry.
> I strongly recommend that this be corrected as soon as possible to ensure clarity and accuracy in our science instruction.

Another from 2024:

> In your "Build an Atom" simulation, why is the atomic mass in the top-left and the atomic number is in the bottom-left? Obviously, this is not the standard. Is this an error or is it intended, as suggested by chatGPT...
> 
> "intended to emphasize the relationship between the number of protons (atomic number) and the element's identity"
