### ISSUE TITLE
Buggly/Freeze Behavior on Win 8 with FF, IE, Chrome

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-an-atom#23]
There is a freezing issue/buggy behavior on Win 8 with FF, IE, and Chrome. Chrome is the best performer, but can still freeze with particles in odd places, and FF is the worst. Seems related to touch events.

**Comment by jbphet** [comment]
We're no longer testing on and fully supporting Win 8 touch devices.  Closing.
