### ISSUE TITLE
branch: symbolNode

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-an-atom#232]
SymbolNode in BAA will become BAASymbolNode and use the generalized SymbolNode from shred as a base class (or it will add it as a child) to avoid duplication of the SymbolNode in IAAM, BAA, and Build a Nucleus - BAN (https://github.com/phetsims/build-a-nucleus/issues/9#issuecomment-1045454629). This branch will be deleted once BAASymbolNode is created and used instead of the current BAA specific SymbolNode.

**Comment by zepumph** [comment]
This has been moved to master and the branch has been deleted. Closing
