### ISSUE TITLE
Spanish "es" translation of Build an Atom is not opening (the sim open in English)

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/build-an-atom#242]
If you go to the Spanish website: https://phet.colorado.edu/es/simulations/build-an-atom and click in the simulation, it is going to open it in English: https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_all.html?locale=es 

But the strings are translated in the translation tool:
<img width="649" alt="image" src="https://github.com/phetsims/build-an-atom/assets/26031501/2966d3c5-a177-466a-b547-9a45331d1999">

Looks like the problem is with the `locale=es` because with the other link, the sim open normal: https://phet.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_es.html

**Comment by zepumph** [comment]
@jonathanolson can you take a look to start?

**Comment by zepumph** [comment]
I wonder if this is related to new locale work, currently being reviewed in https://github.com/phetsims/chipper/issues/1441

**Comment by jonathanolson** [comment]
On it.

**Comment by jonathanolson** [comment]
I think this might be cleanest to build simulations with `--locales=*` instead of only building specific locales. In discussion with @mattpen and @zepumph about it. If not:

build-an-atom 1.6 specific patch to fix:

```diff
Subject: [PATCH] fix patch
---
Index: js/grunt/getBuildConfig.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/grunt/getBuildConfig.js b/js/grunt/getBuildConfig.js
--- a/js/grunt/getBuildConfig.js	(revision 38f062b444c0bb7f75aada161b706d573f929274)
+++ b/js/grunt/getBuildConfig.js	(date 1720460658380)
@@ -347,6 +347,7 @@
 
   buildConfig.licenseKeys = getLicenseKeys( packageJSON, buildJSON, buildConfig.brand, buildConfig.preload );
   buildConfig.locales = getLocales( grunt, buildConfig.name );
+  buildConfig.allLocales = getLocalesFromRepository( buildConfig.name );
   buildConfig.availableLocales = [ ChipperConstants.FALLBACK_LOCALE ].concat( getLocalesFromRepository( buildConfig.name ) );
 
   grunt.log.debug( 'buildConfig=' + JSON.stringify( buildConfig, null, 2 ) );
Index: js/grunt/createHTMLFiles.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/grunt/createHTMLFiles.js b/js/grunt/createHTMLFiles.js
--- a/js/grunt/createHTMLFiles.js	(revision 38f062b444c0bb7f75aada161b706d573f929274)
+++ b/js/grunt/createHTMLFiles.js	(date 1720460695382)
@@ -229,13 +229,13 @@
     // Always include the fallback (en)
     var includedDataLocales = [ ChipperConstants.FALLBACK_LOCALE ];
     // Include directly-used locales
-    buildConfig.locales.forEach( function( locale ) {
+    buildConfig.allLocales.forEach( function( locale ) {
       includedDataLocales.push( locale );
     } );
     // Include locales that will fall back to directly-used locales
     Object.keys( fullLocaleData ).forEach( function( locale ) {
       if ( fullLocaleData[ locale ].fallbackLocales && fullLocaleData[ locale ].fallbackLocales.some( function( fallbackLocale ) {
-        return buildConfig.locales.includes( fallbackLocale );
+        return buildConfig.allLocales.includes( fallbackLocale );
       } ) ) {
         includedDataLocales.push( locale );
       }

```

**Comment by jonathanolson** [comment]
Deploys are going out. I'll check this later or tomorrow.

**Comment by jonathanolson** [comment]
Deploys should be complete. @DianaTavares can you verify?

**Comment by DianaTavares** [comment]
I'm still going to the PhET website ins Spanish and the sim open in English:

<img width="958" alt="image" src="https://github.com/phetsims/build-an-atom/assets/26031501/97ec2633-aab8-479b-9280-634515716173">

that happen in my cellphone and computer, do I need to do something special?

**Comment by zepumph** [comment]
I believe this will be cached until tomorrow.

**Comment by mattpen** [comment]
I checked and the uncached copy is showing the same thing.

To see an uncached copy, change the subdomain to phet-origin and add a random query parameter (e.g. `nonce=something`)

https://phet-origin.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_all.html?locales=es&nonce=4398ty3489

**Comment by zepumph** [comment]
Thanks for the reminder @mattpen, I always forget. I believe the test is `locale=es`, singular. When I do that everything is working well! 

https://phet-origin.colorado.edu/sims/html/build-an-atom/latest/build-an-atom_all.html?locale=es&nonce=4398ty3489fds

@DianaTavares can you confirm.

**Comment by DianaTavares** [comment]
It is working!!
Can I close this issue?

**Comment by zepumph** [comment]
Thanks so much @jonathanolson and @mattpen for the quick work here.
