### ISSUE TITLE
Label visibility panel cannot use decorator pattern

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/build-an-atom#243]
From https://github.com/phetsims/sun/issues/860, UI components with content cannot use the decorator pattern. The checkbox panel in this sim was identified as a usage that decorates a Panel with children. Fix in the following commit, @jbphet can you please review or change the way you would like?

**Comment by jbphet** [comment]
I'm okay with this change, and I verified that it looks good on main, so I'll close.  I think if we wanted to do a more thorough update we would use a `VBox` to create the panel contents, but I started down this road and it just didn't seem worth the time.
