### ISSUE TITLE
Sluggish on Firefox Win 7

### ISSUE THREAD

**Issue by jessegarrison** [phetsims/build-an-atom#36]
It feels very slow when dragging up protons, neutrons, and electrons.  Takes longer than it seems like it should after dropping the item for it to move into place.

Windows 7 Home, 64bit, SP1

Troubleshooting information
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.2/build-an-atom_en.html
Version: 1.1.0-rc.1
Features missing: flexbox, touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0
Language: en-US
Window: 1280x862
Pixel Ratio: 1/1

**Comment by jbphet** [comment]
It's been a while since we've looked at this, so I'm assigning it to @phet-steele to determine whether it's still an issue or can be closed.

**Comment by phet-steele** [comment]
Tested most recent versions of Chrome and FF on both Windows 7 & 8.1. 1.2.0-dev.2 performed admirably.
