### ISSUE TITLE
Electrons Offset from Orbital

### ISSUE THREAD

**Issue by emily-phet** [phetsims/build-an-atom#41]
The electron particles looking offset from the orbital diagram.

![photo 5](https://f.cloud.github.com/assets/5109055/1312216/dddb9e3a-3229-11e3-813c-32990493d474.JPG)

Sim Info:
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.2/build-an-atom_en.html
Version 1.1.0-rc.1
Feature missing: touch, webgl, fullscreen
Flags: msPointerEnabled
User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.050727; .NET CLR 3.0.30729; Tablet PC 2.0; ASU2JS)
Window: 2277x1122
Pixel Ratio: 1/1

**Comment by jbphet** [comment]
This sim has been published for 2+ years and we haven't heard any reports of this.  Also, it seems like very few of our users are on Windows Surface devices.  I think it's safe to close this.
