### ISSUE TITLE
Cannot remove all protons on Windows 8 Surface Chrome

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#42]
In the Atom section; If you add 7 or more protons to the atom with the stable/unstable box unchecked you cannot remove the last proton. The last proton does not respond to touch.

Name: Build an Atom

URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.2/build-an-atom_en.html

Version: 1.1.0-rc.1

User Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.62 Safari/537.36

Language: en-US

Window: 1280x622

Pixel Ratio: 1/1

**Comment by jbphet** [comment]
We're no longer testing on and fully supporting Win 8 touch devices.  Closing.
