### ISSUE TITLE
Very slow Performance Windows 8 Surface Firefox

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#43]
Very slow performance when moving electrons, protons, and neutrons. Response is fine but objects move across the screen with a significant lag.

Name: Build an Atom

URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.2/build-an-atom_en.html

Version: 1.1.0-rc.1

Features missing: flexbox

Flags: pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0

Language: en-US

Window: 1280x595

Pixel Ratio: 1.5/1

**Comment by jbphet** [comment]
We're no longer testing on and fully supporting Win 8 touch devices.  Closing.
