### ISSUE TITLE
Sound choppy / has a stutter in WinXP Chrome

### ISSUE THREAD

**Issue by learnthinkteach** [phetsims/build-an-atom#47]
Sound comes out choppy / has a stutter.
WinXP Chrome.

Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.2/build-an-atom_en.html
Version: 1.1.0-rc.1
Features missing: csstransforms3d, touch
User Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36
Language: en-US
Window: 899x534
Pixel Ratio: 1/1

**Comment by jbphet** [comment]
Closing, since WinXP is no longer a supported platform.
