### ISSUE TITLE
Decreased sensitivity and slow performance when removing particles on Windows Surface

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#54]
Test device: Windows Surface
Operating System: Windows 8 Pro 64-bit
Browser: Firefox 24.0
Troubleshooting Information (from About dialog):

Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.3/build-an-atom_en.html
Version: 1.1.0-rc.3
Features missing: flexbox
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0
Language: en-US
Window: 1280x595
Pixel Ratio: 1.5/1

Description:

Poor touch sensitivity when attempting to remove or place particles. Overall sluggish motion. Very difficult to remove particles.

Steps to reproduce:

Go to the "Atom" or "Symbol" section of the sim. Add all the protons, neutrons, and electrons to the atom. 

Severity:

Sluggish, hard to interact.

**Comment by jbphet** [comment]
We're no longer testing on and fully supporting Win 8 touch devices.  Closing.
