### ISSUE TITLE
While moving objects, object's position flashes along with screen on Chrombook

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#58]
Test device: Samsung Chromebook
Operating system:
Browser: Google Chrome 31.0.1650.26

Troubleshooting information (don't edit this):
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.3/build-an-atom_en.html
Version: 1.1.0-rc.3
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS armv7l 4731.31.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.26 Safari/537.36
Language: en-US
Window: 1162x650
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: false

Description:
Screen flashes rapidly and objects on screen vanish momentarily. Also when you move any particle and let go, the motion along its path is not continuous. The particle flashes and jumps between different points in its path rapidly. 

Steps to reproduce:
Build an atom in either the "Atom" or "Symbol" tab with 4+ electrons 2+ protons 1+ neutrons.
Move particles as if you wanted to rearrange them.

Severity:
Hard to build larger atoms, but is visually difficult at some points.

Screenshots:
(Screenshot is at one moment during rapid flashing)
![baa bug chromebook](https://f.cloud.github.com/assets/5631059/1393330/c130f502-3c18-11e3-968a-ee723372f72a.png)

**Comment by jbphet** [comment]
Assigning to @phet-steele to see if this can be reproduced on a Chromebook.  If not, it can be closed.

**Comment by phet-steele** [comment]
Tested 1.2.0-dev.2 on two chromebooks, both build 7647.73.0 and browser 48.0.2564.92.

Firmware for each:
Peppy.4389.93.0 (Acer)
Snow.2695.117.0 (Samsung)

Everything performed exceptionally on these two devices :+1:
