### ISSUE TITLE
Safari: everything disappears?

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-an-atom#63]
Report a Problem

Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks. 

Test device: Macbook Air 

Operating System: OSX 10.8.5

Browser: 6.0.5 Safari/536.30.1

Problem description: Opened BAA in safari and did some emailing in Chrome. When I came back to the sim everything in the play area had disappeared except the menu button and home buttons (which worked)

Steps to reproduce: I am going to try to open the sim and leave it while looking at other windows.

Severity:

Screenshots:
![image](https://f.cloud.github.com/assets/5090275/1433815/d938456e-4100-11e3-9bd1-06138be8a563.png)
![image](https://f.cloud.github.com/assets/5090275/1433817/e8c764e2-4100-11e3-94c3-f1380cf6cf45.png)

Troubleshooting information (do not edit):
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.4/build-an-atom_en.html
Version: 1.1.0-rc.4
Features missing: flexbox, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/536.30.1 (KHTML, like Gecko) Version/6.0.5 Safari/536.30.1
Language: en-us
Window: 1024x579
Pixel Ratio: 1/1
WebGL: disabled

**Comment by phet-steele** [comment]
This never came up during testing on our supported platforms. tried to do it myself for ~10 minutes, couldn't. Closing.
