### ISSUE TITLE
Model selection freezes (Multi-Touch) Windows 8 Laptop

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#65]
Test device: ASUS Sonic Master
Operating System: Windows 8 64-bit
Browser: Google Chrome

Problem description:

The model selection: "Orbits" & "Cloud" freezes if you use the touch screen and the mouse simultaneously. 

Steps to reproduce:
Move a particle with a mouse and hold it down.
While holding that particle touch the screen to select either "Orbits" or "Cloud"
Then which ever you select next it well freeze on and you can no longer change the Model.

Severity:
Only matters if our intentions are to support the touch capabilities of windows 8. 

Troubleshooting information (do not edit):
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc.4/build-an-atom_en.html
Version: 1.1.0-rc.4
User Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36
Language: en-US
Window: 1511x741
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
This is a multi-touch issue on a Windows 8 laptop, so we're not going to worry about it.  Closing.
