### ISSUE TITLE
Consider Slowing Falling Motion of Reward Objects

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-an-atom#66]
On all platforms @ariel-phet tested this motion appears to be choppy, and is quite distracting, consider slowing the falling speed considerably.

**Comment by jbphet** [comment]
@ariel-phet - can you test on the latest master version and decide if this is still and issue?

**Comment by ariel-phet** [comment]
Tested on Win 10 chrome on my pretty fast laptop...still appeared a bit jerky to me. Looks like GC

**Comment by samreid** [comment]
renderer:'webgl' may be a possible avenue for investigation in improved performance, if all of the reward nodes can easily be toImage()d

**Comment by aadish** [comment]
@ariel-phet we reduced the number of nodes for the reward screen and it looks better
can you check the master version and you can use reward as query parameter and it will always give the reward screen whatever the score maybe 
And it should be comparable to all other reward nodes in other simulations as we are using the common code reward node

**Comment by ariel-phet** [comment]
@aadish definitely looks better. I would call it acceptable on my machine now, but I would still reduce the speed of fall a bit (25 percent or so) if possible.

**Comment by aadish** [comment]
@ariel-phet we tested this in firefox and looks far more noticeable as compared to other browsers that is what you were referring to initially

**Comment by ariel-phet** [comment]
@jbphet and I discussed and decided he will make a more general issue in vegas to at some point optimize reward node. This is good enough for now.

Assigning to @jbphet to close this issue once he has made the more general vegas issue.

**Comment by jbphet** [comment]
The common code issue has been created, closing this one.
