### ISSUE TITLE
Make Font for "Element Name", "Neutral/Ion", "Stable/Unstable" somewhat smaller

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/build-an-atom#70]
This is a (albeit last minute) suggestion to reduce the font size (not the check box size) of the option titles for "Element Name", "Neutral/Ion", "Stable/Unstable". They seem a bit bigger and drawing more attention than they need to be, and reducing font size a bit could help add a bit more whitespace around each name which could make it feel less crowded down in that corner even though checkbox size and spacing doesn't change. 

I would perhaps consider matching the font size of "Orbits" "Cloud" or "Protons" "Neutrons' etc. 

This is not a bug - but I was looking at it on Kathy's ThinkPad. And here is screenshot of that corner text. 
![image](https://f.cloud.github.com/assets/5096804/1458479/419f1b56-4376-11e3-808c-8f3a97068409.png)

**Comment by jbphet** [comment]
Assigning to @aadish since I believe that the checkbox size is now an option to Checkbox, so this request can be implemented.

**Comment by aadish** [comment]
this has been fixed, would be tested in next round of testing

**Comment by jbphet** [comment]
Code changes look good, and the panel looks better as well.  Closing.
