### ISSUE TITLE
User reported issue: Home screens overlap

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-an-atom#75]
Reported by Roberto Fanciulli <faro49@gmail.com>

![report a problem-phethelp pdf - adobe reader_-11-12_13-46-21](https://f.cloud.github.com/assets/5090275/1525851/85c44cb2-4bdb-11e3-867b-aa6902d51809.png)
![report a problem-phethelp pdf - adobe reader_-11-12_13-46-17](https://f.cloud.github.com/assets/5090275/1525852/85d196e2-4bdb-11e3-93a0-6eca73f8c0f8.png)

Report a Problem
Please copy and paste the information below into an email to phethelp@colorado.edu, and
then fill in the blanks.
Test device: Desktop PC
Operating System: Windows XP SP3
Browser: Firefox 25.0
Problem description: I downloaded the simulation and run it in the browser. The
three icons that appear on the main page are overlapped (first screenshot) and
when select the first menù item the images are ever overlapped (second
screenshoot).
Steps to reproduce:
Severity:
Screenshots:
Troubleshooting information (do not edit):
Name: Build an Atom
URL:
file:///C:/Documents%20and%20Settings/utente/Desktop/Da%20stampare%20per%20Ale%20%
20e%20Cex/Build%20an%20Atom%201.1.1.htm
Version: 1.1.1
Features missing: flexbox, touch
User Agent: Mozilla/5.0 (Windows NT 5.1; rv:25.0) Gecko/20100101 Firefox/25.0
Language: it-IT
Window: 1280x861
Pixel Ratio: 1/1
WebGL: disabled ([Exception... "Failure" nsresult: "0x80004005 (NS_ERROR_FAILURE)"
location: "JS frame ::
http://phet.colorado.edu/files/troubleshooting/?sim=Build%20an%20Atom&version=1.1.1&url=
file%3A%2F%2F%2FC%3A%2FDocuments%2520and%2520Settings%2Futente%2FDesktop%
2FDa%2520stampare%2520per%2520Ale%2520%2520e%2520Cex%2FBuild%2520an%2520
Atom%25201.1.1.htm :: <TOP_LEVEL> :: line 222" data: no] [Exception... "Failure" nsresult:
"0x80004005 (NS_ERROR_FAILURE)" location: "JS frame ::
http://phet.colorado.edu/files/troubleshooting/?sim=Build%20an%20Atom&version=1.1.1&url=
file%3A%2F%2F%2FC%3A%2FDocuments%2520and%2520Settings%2Futente%2FDesktop%
2FDa%2520stampare%2520per%2520Ale%2520%2520e%2520Cex%2FBuild%2520an%2520
Atom%25201.1.1.htm :: <TOP_LEVEL> :: line 222" data: no] [Exception... "Failure" nsresult:
"0x80004005 (NS_ERROR_FAILURE)" location: "JS frame ::
http://phet.colorado.edu/files/troubleshooting/?sim=Build%20an%20Atom&version=1.1.1&url=
file%3A%2F%2F%2FC%3A%2FDocuments%2520and%2520Settings%2Futente%2FDesktop%
2FDa%2520stampare%2520per%2520Ale%2520%2520e%2520Cex%2FBuild%2520an%2520
Atom%25201.1.1.htm :: <TOP_LEVEL> :: line 222" data: no] )

**Comment by jbphet** [comment]
This issue is about 2.5 years old and we haven't seen it or heard any other reports of it.  I'm going to assume that something got fixed in the browser(s) and/or Scenery that made this go away.  Closing.
