### ISSUE TITLE
User report screen turns black after many particles added

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#76]
From Facebook:

Mathias Tomandl commented on a link PhET Interactive Simulations shared.
Mathias wrote: "Hi, if I add more than 18 particles to the atom my screen turns black.. can you reproduce that?"

**Comment by phet-steele** [comment]
Yea definitely not happening on Chrome 50.0.2661.75 m (64-bit) Win 10:
![goodchrome](https://cloud.githubusercontent.com/assets/5863899/14692770/b3884ad8-0716-11e6-885b-1e7ebb70be11.PNG)
