### ISSUE TITLE
Game screen displays only blue box.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/build-an-atom#79]
Test device: Mac Book Pro 13" 
Operating System: OS X 10.6.8
Browser: Safari 5.1.7
Problem description:
Game screen only displays blue box. Games are no longer playable with out completely refreshing the sim page.

Steps to reproduce:
Open sim.
Select "Game" screen
Select any of the 4 game selections

Severity:
Games are unplayable. Should be fixed.

Screenshots:

![baa-1 1 2-rc 2gamescreenbluebug](https://f.cloud.github.com/assets/5631059/1576149/54ee6ef6-5158-11e3-8ba1-9523b3bf4646.png)

Troubleshooting information (do not edit):
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.2-rc.2/build-an-atom_en.html
Version: 1.1.2-rc.2
Features missing: flexbox, touch, raf, svgfilters
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2
Language: en-us
Window: 800x541
Pixel Ratio: 1/1
WebGL: disabled

**Comment by jbphet** [comment]
Fixed long ago, closing.
