### ISSUE TITLE
consider changing color of level-selection buttons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#90]
After converting to the new vegas.LevelSelectionButton (see phetsims/vegas#36), the level-selection buttons look a bit lost, their color is too similar to the background. See screenshots below. 

Old buttons:
![screenshot_194](https://cloud.githubusercontent.com/assets/3046552/5945946/5fdcafe2-a6ef-11e4-87c6-786989d97588.png)

New buttons:
![screenshot_193](https://cloud.githubusercontent.com/assets/3046552/5945950/629b004e-a6ef-11e4-8864-ed1dc66d2e16.png)

**Comment by ariel-phet** [comment]
Checked latest pull.

Purple, love it! Also checked in grayscale view, and no obvious issues with color choice. Closing
