### ISSUE TITLE
Properties should have `Property` suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#94]
See https://github.com/phetsims/beers-law-lab/issues/86

Examples of anti pattern (not exhaustive):

CountsToChargeProblemView: this.chargeAnswer = new Property( 0 );
CountsToMassNumberProblemView: this.massNumberAnswer = new Property( 0 );
InteractiveSymbolNode: thisNode.protonCount = new Property( options.interactiveProtonCount ? 0 : numberAtom.protonCount );
InteractiveSymbolNode: thisNode.massNumber = new Property( options.interactiveMassNumber ? 0 : numberAtom.massNumber );
InteractiveSymbolNode:  thisNode.charge = new Property( options.interactiveCharge ? 0 : numberAtom.charge );

**Comment by jbphet** [comment]
@aadish is currently working on cleanup of this simulation, assigning to him for resolution.

**Comment by aadish** [comment]
fixed, closing
